version: '3.8'

services:
  searxng:
    image: searxng/searxng:latest
    ports:
      - "4000:8080"
    networks:
      - themis-network
    volumes:
      - ./searxng/settings.yml:/etc/searxng/settings.yml

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    networks:
      - themis-network

  perplexica-frontend:
    image: itzcrazykns1337/perplexica:latest
    ports:
      - "3005:3000"
    networks:
      - themis-network
    depends_on:
      - ollama
      - searxng
    volumes:
      - perplexica-root:/home/perplexica
      - C:/Users/inoub/Perplexica/config.toml:/home/perplexica/config.toml:ro

networks:
  themis-network: {}

volumes:
  ollama-data: {}
  perplexica-root: {}















 




